### ISSUE TITLE
following the instructions in the readme and i get this error

### ISSUE THREAD

**Issue by cameronbergh** [hcdiekmann/pathfinder#1]
in an ubuntu 20.04 arm64 virtual machine:

cameron@ubuntu-20:~/pathfinder_ws$ ros2 launch pathfinder single_bot_sim.launch.py world:=~/ros2_ws/src/pathfinder/worlds/pathfinder_test.world
[INFO] [launch]: All log files can be found below /home/cameron/.ros/log/2023-03-03-14-26-43-862746-ubuntu-20-9204
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [9206]
[INFO] [gzserver-2]: process started with pid [9209]
[INFO] [gzclient   -3]: process started with pid [9211]
[INFO] [spawn_entity.py-4]: process started with pid [9222]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Error:   No name given for the robot.
[robot_state_publisher-1]          at line 89 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/model.cpp
[robot_state_publisher-1] terminate called after throwing an instance of 'std::runtime_error'
[robot_state_publisher-1]   what():  Unable to initialize urdf::model from robot description
[ERROR] [gzserver-2]: process has died [pid 9209, exit code 255, cmd 'gzserver ~/ros2_ws/src/pathfinder/worlds/pathfinder_test.world                                                                      -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so   -s libgazebo_ros_force_system.so       '].
[spawn_entity.py-4] [INFO] [1677882404.478082093] [spawn_entity]: Spawn Entity started
[spawn_entity.py-4] [INFO] [1677882404.478487334] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-4] [INFO] [1677882404.479427769] [spawn_entity]: Waiting for entity xml on robot_description
[ERROR] [robot_state_publisher-1]: process has died [pid 9206, exit code -6, cmd '/opt/ros/foxy/lib/robot_state_publisher/robot_state_publisher --ros-args --params-file /tmp/launch_params_868srxkx'].
[gzclient   -3] Aborted (core dumped)
[ERROR] [gzclient   -3]: process has died [pid 9211, exit code 134, cmd 'gzclient   '].

**Comment by hcdiekmann** [comment]
Should be fixed now with the latest commits. Let me know if the error persists.

**Comment by cameronbergh** [comment]
Awesome! 

after doing:
'git pull'
 'rm -rf build/ install/ log/'
'colcon build --symlink-install'

 i am able to run the gazebo sim.
