### ISSUE TITLE
teleop_twist_keyboard doesnt move the bot?

### ISSUE THREAD

**Issue by cameronbergh** [hcdiekmann/pathfinder#2]
I am very new to ROS, so perhaps i am doing it wrong. but anyway. 

teleop_twist_keyboard seems to run okay but i dont get any movement out of the robot in gazebo

cameron@ubuntu-20:~/pathfinder_ws$ ros2 node list -a
/_ros2cli_daemon_65
/gazebo
/robot_state_publisher
/teleop_twist_keyboard

I was able to get the turtlesim keyboard thing to work so it would seem like the teleop_twist_keyboard should also work but i dont know

**Comment by cameronbergh** [comment]
i love this project, i am trying to figure out ros as well and this project is super helpful!

**Comment by hcdiekmann** [comment]
Running `$ ros2 topic list` should give at least these topics:
```bash
/clock
/cmd_vel
/joint_states
/parameter_events
/robot_description
/rosout
/tf
/tf_static
```

For the teleop_twist_keyboard node, it is important that the terminal running the node is in focus to listen for keystrokes

**Comment by hcdiekmann** [comment]
I have tested and confirmed this works on Ubuntu 20.04 with Foxy. I will close this issue now, but feel free to keep commenting.
