### ISSUE TITLE
view_lidar_sim.rviz doesnt exist.

### ISSUE THREAD

**Issue by cameronbergh** [hcdiekmann/pathfinder#3]
on the readme this line

 rviz2 -d src/pathfinder/config/view_lidar_sim.rviz   

will launch rviz but this file dosnt exist.

**Comment by hcdiekmann** [comment]
Added the RViz configuration file back with the [commit](https://github.com/hcdiekmann/pathfinder/commit/b7f890e7ace28e82f31b9c28caf98c68c4dcad5e)

**Comment by hcdiekmann** [comment]
I will close this issue as completed.
